### PR TITLE
Update README with signing instructions

### PR DESCRIPTION
**Pull request by Jawnnypoo**
Another follow up for https://github.com/vanniktech/gradle-maven-publish-plugin/issues/71

### CODE REVIEW

**Comment by Jawnnypoo** [comment]
I think Travis is stuck on this one.

**Comment by Jawnnypoo** [comment]
Is this good to merge now?

**Comment by vanniktech** [comment]
Yes. Forgot about it

**Comment by vanniktech** [comment]
Many thanks!

**Pull request merged**
