### PR TITLE
Use srcDirs instead of sourceFiles to include Kotlin files to sources jar

### PR DESCRIPTION
**Pull request by lukaville**
#47

### CODE REVIEW

**Comment by vanniktech** [comment]
Thank you :)

**Comment by ZacSweers** [comment]
I've tried this out locally but am still not seeing kotlin sources included. Test project https://github.com/InflationX/ViewPump

**Comment by vanniktech** [comment]
So, I've tested this out on https://github.com/vanniktech/RxBilling/tree/kotlin-sources

and when using `installArchives` I can see `~/.m2/repository/com/vanniktech/rxbilling-testing/0.3.0-SNAPSHOT/rxbilling-testing-0.3.0-20190311.102147-1-sources.jar` being generated. Also when I unzip that jar file I can see the Kotlin file. This is a kotlin only module.

For Android + Kotlin I've also got - https://github.com/vanniktech/Emoji/tree/kotlin-sources - which seems to be working.

I've checked out your use case and there are no sources being generated - which is weird. I've also tried around but I simply could not get it to work. It also seems weird since it does not differ a lot from the projects where I'm running it on.

I can also publish this plugin using the version from master and then I'll see sources too. Do you have any clue that can cause the fact that ViewPump does not work? @ZacSweers

**Comment by vanniktech** [comment]
@ZacSweers I've created https://github.com/vanniktech/ViewPump/tree/sources which uses a local version of the plugin (you can publish it via `installArchives`) and I've noticed that the `androidJavadocsJar` task isn't called when I run `installArchives`. In my projects it is which is weird. If that one isn't called we don't do anything related with dokka so the set up that we're having is brittle.

**Comment by ZacSweers** [comment]
in the end - the viewpump issue turned out to be that it was using the wrong dokka plugin artifact 😭

**Pull request merged**
